strategy.symbols=GOLDM05AUG26FUT
#1594
# Example for INFY Equity (Buy on breakout)
strategy.INFY-EQ.entryPrice=1450.0
strategy.INFY-EQ.stopLossPrice=1440.0
strategy.INFY-EQ.targetPrice=1470.0
strategy.INFY-EQ.trailingSlPoints=2.0
strategy.INFY-EQ.quantity=100
strategy.INFY-EQ.transactionType=BUY
strategy.INFY-EQ.exchange=NSE
strategy.INFY-EQ.product=MIS
# For equity, buy when price falls to or below entry
strategy.INFY-EQ.entryCondition=LESS_THAN_EQUAL

# Example for NIFTY Options
# Replace NIFTY-OPT with actual symbol from Scrip Master (e.g. NIFTY14JUL2624000CE)
# strategy.NIFTY-OPT.entryPrice=120.0
# strategy.NIFTY-OPT.stopLossPrice=100.0
# strategy.NIFTY-OPT.targetPrice=180.0
# strategy.NIFTY-OPT.trailingSlPoints=5.0
# strategy.NIFTY-OPT.quantity=50
# strategy.NIFTY-OPT.transactionType=BUY
# strategy.NIFTY-OPT.exchange=NFO
# strategy.NIFTY-OPT.product=NRML

strategy.GOLDM05AUG26FUT.entryPrice=152960.0
strategy.GOLDM05AUG26FUT.stopLossPrice=152560.0
strategy.GOLDM05AUG26FUT.targetPrice=162960.0
strategy.GOLDM05AUG26FUT.trailingSlPoints=50.0
strategy.GOLDM05AUG26FUT.quantity=1
strategy.GOLDM05AUG26FUT.transactionType=BUY
strategy.GOLDM05AUG26FUT.exchange=MCX
strategy.GOLDM05AUG26FUT.product=NRML


strategy.NIFTY14JUL2624000CE.entryPrice=120.0
strategy.NIFTY14JUL2624000CE.stopLossPrice=100.0
strategy.NIFTY14JUL2624000CE.targetPrice=180.0
strategy.NIFTY14JUL2624000CE.trailingSlPoints=5.0
strategy.NIFTY14JUL2624000CE.quantity=50
strategy.NIFTY14JUL2624000CE.transactionType=BUY
strategy.NIFTY14JUL2624000CE.exchange=NFO
strategy.NIFTY14JUL2624000CE.product=NRML
# As requested, options should use >= condition
strategy.NIFTY14JUL2624000CE.entryCondition=GREATER_THAN_EQUAL
