# MStock API endpoints
mstock.api.login=https://api.mstock.trade/openapi/typeb/connect/login
mstock.api.verify_totp=https://api.mstock.trade/openapi/typeb/session/verifytotp
mstock.api.instruments=https://api.mstock.trade/openapi/typeb/instruments/OpenAPIScripMaster

# AngelOne API endpoints
angelone.api.login=https://apiconnect.angelbroking.com/rest/auth/angelbroking/user/v1/loginByPassword
angelone.api.instruments=https://margincalculator.angelbroking.com/OpenAPI_File/files/OpenAPIScripMaster.json

# Dhan API endpoints
dhan.api.login=https://auth.dhan.co/app/generateAccessToken

# Groww API endpoints
groww.api.login=https://api.groww.in/v1/token/api/access
groww.api.instruments=https://growwapi-assets.groww.in/instruments/instrument.csv
groww.api.holdings=https://api.groww.in/v1/holdings/user
groww.api.positions=https://api.groww.in/v1/positions/user
groww.api.profile=https://api.groww.in/v1/user/profile
